#!/bin/sh

echo Nuclear Instruments R5560 Startup


#!/bin/sh
### BEGIN INIT INFO
# Provides:           load-config
# Required-Start      
# Required-Stop       
# Default-Start       S
# Default-Stop:       
# Short-Description:  Startup
### END INIT INFO

S=/mnt/sdcard
D=/etc/yourapplication
C=startup.sh

if [ "$1" != "start" ]; then
    exit 0
fi

# create directories/files
mkdir -p ${S}
mkdir -p ${D}

echo ""
echo ""
echo ""
echo ""
echo "--------------------------------------------"
echo "-        NUCLEAR INSTRUMENTS R5560         -"
echo "-                                          -"
echo "-       IMAGE VERSION: 2021.10.27.01       -"
echo "-                                          -"
echo "-       loading firmware and daemons       -"
echo "--------------------------------------------"
echo ""
echo ""

echo "** Mounting SD-CARD"
# mount the sd card
mount /dev/mmcblk0p1 ${S}

if [ -f ${S}/${C} ]; then
    echo "Running startup script"
    cp ${S}/${C} ${D}/${C}
    source ${D}/${C}
else
    echo "No startup script file found"
fi

echo "** Loading persistent etc from SDCARD"
# Load /etc files
if [ -d ${S}/etc ]; then
    echo "Loading /etc from SD"
    cp -rv ${S}/etc/* /etc/
fi


echo "** Uploading firmware of fpga..."
# if bitfile exists on SD card, program it
if [ -f ${S}/firmware.fpga ]; then
    echo "Firmware file found, programming"
    mkdir -p /lib/firmware
    cp ${S}/firmware.fpga /lib/firmware/firmware.bin
    echo "Programming FPGA"
    echo firmware.bin > /sys/class/fpga_manager/fpga0/firmware
fi

echo "** Firmware current status is"
cat /sys/class/fpga_manager/fpga0/state

echo "** Loading ethernet interfaces file from SDCARD"
cp ${S}/interfaces /etc/network/interfaces

#umount ${S}

if grep -q operating /sys/class/fpga_manager/fpga0/state
then

    #FPGA is programmed

    echo ""
    echo ""
    echo ""
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
    echo "****** HIT ANY KEY TO ENTER IN RECOVERY MODE ******"
    echo "**** R5560 daemons will be loaded in 3 seconds ****"
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
    echo ""

    read -n 1 -t 3
    if [ $? == 0 ]; then
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
    echo "******                                       ******"
    echo "****              RECOVERY MODE                ****"
    echo "******                                       ******"
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
        
        exit 0
    fi


    # set hostname again, in case it changed
    #/etc/init.d/hostname.sh


    adcinit
    configdaemon &

    nibridge &
    exit 0


else
    i2cset -y 0 0x20 0x3 0x0
    i2cset -y 0 0x20 0x1 0xFE
    echo ""
    echo ""
    echo ""
    echo ""    
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo "******     R5560 ENTERED IN RECOVERY MODE    ******"
    echo "**** Invalid or no firmware is loaded on FPGA  ****"
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo ""
    echo ""
    echo ""
    echo ""
    echo ""
fi


ifdown eth0
ifup eth0

